### Data Acquisition

In [1]:
import pandas as pd

expendituresDataFrame = pd.read_csv("independentExpenditures2024.csv")
expendituresDataFrame.head()
#Olivia - Find a data set of the current senate (so we can determine if there is a correlation between winning an election and amount spent by PACs) w/ gender

,cand_id,cand_name,spe_id,spe_nam,ele_type,can_office_state,can_office_dis,can_office,cand_pty_aff,exp_amo,...,pur,pay,file_num,amndt_ind,tran_id,image_num,receipt_dat,fec_election_yr,prev_file_num,dissem_dt
0,H4CO08034,"Evans, Gabe",C00866517,Go America PAC,G,CO,8.0,H,REPUBLICAN PARTY,9000.00,...,texts supporting Gabe Evans CO-8,TTHM.com,1845617,N,E2D2833410CAA40CB9A5,202410319719900778,31-OCT-24,2024,NaN,30-OCT-24
1,P80000722,"Harris, Kamal D",C00877886,1000 Women Strong PAC,G,NaN,0.0,P,DEMOCRATIC PARTY,50000.00,...,Advertising Services,Northwind Strategies,1820306,N,SE.4111,202410049684791551,04-OCT-24,2024,NaN,02-OCT-24
2,P80000722,"Harris, Kamal D",C00877886,1000 Women Strong PAC,G,NaN,0.0,P,DEMOCRATIC PARTY,15000.00,...,Estimated costs of consultant work,1000 Women Strong PAC,1820306,N,SE.4109,202410049684791550,04-OCT-24,2024,NaN,02-OCT-24
3,P80000722,"Harris, Kamal D",C00877886,1000 Women Strong PAC,G,NaN,0.0,P,DEMOCRATIC PARTY,7000.00,...,Production Costs for Ads,Corsair Communications,1820306,N,SE.4110,202410049684791550,04-OCT-24,2024,NaN,02-OCT-24
4,S4MD00327,"Alsobrooks, Angela",C90022559,1199 SEIU New York State Political Action Fund,G,MD,0.0,S,DEMOCRATIC PARTY,864.15,...,Direct Mail Production and Distribution (Estim...,Pendulum Creative Group,1845172,N,510110468,202410309719846853,30-OCT-24,2024,NaN,NaN

### Data Cleaning and Processing

In [2]:
# LIV - FILTER FOR ONLY SENATE CANDIDATES

# office_groups = expendituresDataFrame.groupby("can_office")
# print(office_groups.groups.keys())
# The values of can_office are H, P, or S where H = House, P = President, and S = Senate

# mask to filter for only senate candidates:
senate_mask = expendituresDataFrame["can_office"] == "S"

# applying mask to main dataframe since we are limiting our scope to only senate candidates
expendituresDataFrame = expendituresDataFrame[senate_mask].reset_index()
expendituresDataFrame.head()

,index,cand_id,cand_name,spe_id,spe_nam,ele_type,can_office_state,can_office_dis,can_office,cand_pty_aff,...,pur,pay,file_num,amndt_ind,tran_id,image_num,receipt_dat,fec_election_yr,prev_file_num,dissem_dt
0,4,S4MD00327,"Alsobrooks, Angela",C90022559,1199 SEIU New York State Political Action Fund,G,MD,0.0,S,DEMOCRATIC PARTY,...,Direct Mail Production and Distribution (Estim...,Pendulum Creative Group,1845172,N,510110468,202410309719846853,30-OCT-24,2024,NaN,NaN
1,5,S4MD00327,"Alsobrooks, Angela",C90022559,1199 SEIU New York State Political Action Fund,G,MD,0.0,S,DEMOCRATIC PARTY,...,Event Coordination (Estimate),DT Event Consulting,1847462,N,508110469,202411039719921574,03-NOV-24,2024,NaN,NaN
2,6,S6PA00217,"Casey, Bob",C90022559,1199 SEIU New York State Political Action Fund,G,PA,0.0,S,DEMOCRATIC PARTY,...,Direct Mail Production and Distribution (Estim...,Pendulum Creative Group,1845172,N,590110460,202410309719846856,30-OCT-24,2024,NaN,NaN
3,101,S4MD00327,"ALSOBROOKS, ANGELA",C00348540,1199 SEIU United Healthcare Workers East Feder...,G,MD,0.0,S,DEMOCRATIC PARTY,...,Radio and Digital Ad Buy and Production (Estim...,Karen Miller Consulting LLC,1832009,N,500117274,202410189698743719,18-OCT-24,2024,NaN,17-OCT-24
4,118,S4MT00183,"SHEEHY, TIM",C00881482,1889 PAC,G,MT,0.0,S,REPUBLICAN PARTY,...,"Mail Printing, Production, & Postage",Pathfinder Communications,1794189,N,SE.4113,202407079652573607,07-JUL-24,2024,NaN,05-JUL-24

In [3]:
#LIV - CAND_PTY_AFF_SIMPL CATEGORY
# adding a cand_pty_aff_simpl category, where 'D' = democrat, 'R' = republican, and 'O' = all other notations from cand_party_aff column, including na





simplified_parties = []

for row in range(len(expendituresDataFrame)):
    candidate_party = expendituresDataFrame.loc[row]["cand_pty_aff"]
    if candidate_party == "DEMOCRATIC PARTY":
        simplified_parties.append("D")
    elif candidate_party == "REPUBLICAN PARTY":
        simplified_parties.append("R")
    else:
        simplified_parties.append("O")


expendituresDataFrame["cand_pty_aff_simpl"] = simplified_parties



expendituresDataFrame.head()

,index,cand_id,cand_name,spe_id,spe_nam,ele_type,can_office_state,can_office_dis,can_office,cand_pty_aff,...,pay,file_num,amndt_ind,tran_id,image_num,receipt_dat,fec_election_yr,prev_file_num,dissem_dt,cand_pty_aff_simpl
0,4,S4MD00327,"Alsobrooks, Angela",C90022559,1199 SEIU New York State Political Action Fund,G,MD,0.0,S,DEMOCRATIC PARTY,...,Pendulum Creative Group,1845172,N,510110468,202410309719846853,30-OCT-24,2024,NaN,NaN,D
1,5,S4MD00327,"Alsobrooks, Angela",C90022559,1199 SEIU New York State Political Action Fund,G,MD,0.0,S,DEMOCRATIC PARTY,...,DT Event Consulting,1847462,N,508110469,202411039719921574,03-NOV-24,2024,NaN,NaN,D
2,6,S6PA00217,"Casey, Bob",C90022559,1199 SEIU New York State Political Action Fund,G,PA,0.0,S,DEMOCRATIC PARTY,...,Pendulum Creative Group,1845172,N,590110460,202410309719846856,30-OCT-24,2024,NaN,NaN,D
3,101,S4MD00327,"ALSOBROOKS, ANGELA",C00348540,1199 SEIU United Healthcare Workers East Feder...,G,MD,0.0,S,DEMOCRATIC PARTY,...,Karen Miller Consulting LLC,1832009,N,500117274,202410189698743719,18-OCT-24,2024,NaN,17-OCT-24,D
4,118,S4MT00183,"SHEEHY, TIM",C00881482,1889 PAC,G,MT,0.0,S,REPUBLICAN PARTY,...,Pathfinder Communications,1794189,N,SE.4113,202407079652573607,07-JUL-24,2024,NaN,05-JUL-24,R

In [4]:
largeDonationCutoff = 1000000 #1,000,000

# !!! For anything regarding the size of the donation, use exp_amo (expenditure amount) !!!
# !!! The other variable (agg_amo) is the total amount of money that PAC has spent !!!

#Sam - Standardize names with IDs, throw away entries that dont match anything else. Can use district, id, and name to filter.

#Liv - Drop all donations that are not to a republican or democrat


#Liv - Create a new column titled "cand_pty_aff_bool" where a republican would be True and a democrat would be false. (could also add support for multiple parties

# Liv - create dataset for current senate members

# Liv - add boolean gender markers for current senate members; true = male false = female

#Sam - Create a new column for supporting/opposing converted to true/false (let supporting = true opposing = false)

#Sam - Create a new data frame with just donations > largeDonationCutoff

#Sam - Create data frame for swing states (up to you how you wanna do this)

#Jake - Create a new data frame for true republican / true democrat expenditures. Example: A donation could be for a republican candidate but be in opposition.
# In that case, it would be a democrat donation because its opposing a republican

#Jake - Create a new data frame from this true expenditure data frame filtered by the aforementioned donation cutoff

#Feel free to add anything else we need to do


republicanExpendituresDataFrame = expendituresDataFrame[expendituresDataFrame['cand_pty_aff'] == "REPUBLICAN PARTY"] #Donations to republican candidates either supposing or opposing
democratExpendituresDataFrame = expendituresDataFrame[expendituresDataFrame['cand_pty_aff'] == "DEMOCRATIC PARTY"] #Donations to democratic candidates either supposing or opposing

largeRepublicanExpendituresDataFrame = republicanExpendituresDataFrame[republicanExpendituresDataFrame['exp_amo'] > largeDonationCutoff]
largeDemocratExpendituresDataFrame = democratExpendituresDataFrame[democratExpendituresDataFrame['exp_amo'] > largeDonationCutoff]

republicanExpendituresDataFrame.head()
democratExpendituresDataFrame.head()
largeRepublicanExpendituresDataFrame.head()
largeDemocratExpendituresDataFrame.head()

,index,cand_id,cand_name,spe_id,spe_nam,ele_type,can_office_state,can_office_dis,can_office,cand_pty_aff,...,pay,file_num,amndt_ind,tran_id,image_num,receipt_dat,fec_election_yr,prev_file_num,dissem_dt,cand_pty_aff_simpl
844,7026,S6OH00163,"BROWN, SHERROD",C00487363,American Crossroads,G,OH,0.0,S,DEMOCRATIC PARTY,...,MAIN STREET MEDIA GROUP,1818426,N,SE.1,202409249684705100,24-SEP-24,2024,NaN,24-SEP-24,D
849,7031,S6OH00163,"BROWN, SHERROD",C00487363,American Crossroads,G,OH,0.0,S,DEMOCRATIC PARTY,...,GEN2 SOLUTIONS LLC,1816070,N,SE.5,202409179675508116,17-SEP-24,2024,NaN,17-SEP-24,D
850,7032,S6OH00163,"BROWN, SHERROD",C00487363,American Crossroads,G,OH,0.0,S,DEMOCRATIC PARTY,...,MAIN STREET MEDIA GROUP,1816070,N,SE.1,202409179675508115,17-SEP-24,2024,NaN,17-SEP-24,D
853,7035,S6OH00163,"BROWN, SHERROD",C00487363,American Crossroads,G,OH,0.0,S,DEMOCRATIC PARTY,...,MAIN STREET MEDIA GROUP,1827502,N,SE.1,202410159686527142,15-OCT-24,2024,NaN,15-OCT-24,D
855,7037,S6OH00163,"BROWN, SHERROD",C00487363,American Crossroads,G,OH,0.0,S,DEMOCRATIC PARTY,...,MAIN STREET MEDIA GROUP,1819413,N,SE.1,202410019684773751,01-OCT-24,2024,NaN,01-OCT-24,D

### Exploratory Analysis

#### These are the questions from the project proposal. We can add/remove questions as wanted.

#### Jake - How much money do candidates in political parties receive opposing them and supporting them? What are their largest donors?

#### Sam - Are supporting or opposing donations bigger?  More common? How do they lean politically?

#### What are the biggest Super PACs donating? Where do they primarily donate and generally how do they lean politically?

In [5]:
#This is where you can use agg_amo

#### Jake - Which political parties receive larger single donations, or donations from a single group?  Which receives smaller donations? Which receives a higher quantity of donations?

#### Jake - Does the size of a donation correlate with Republican or Democrat?

In [6]:
# Im not sure how to visualize this but maybe a scatter plot colored by part affiliation?

#### Olivia - What effect do these donations have on the current Senate?

#### Sam - How do swing states differ than non swing states

In [7]:
# Arizona, Georgia, Michigan, Nevada, Pennsylvania, and Wisconsin were the swing states in 2024

#### Jake - Where do donations differ?

In [8]:
print("The number of Republican SUPER PACs expenditures from 2022-24 is " + str(republicanExpendituresDataFrame.size))
print("The number of Democrat SUPER PACs expenditures from 2022-24 is " + str(democratExpendituresDataFrame.size))

print("The number of large Republican SUPER PACs expenditures (>$1,000,000) from 2022-24 is " + str(largeRepublicanExpendituresDataFrame.size))
print("The number of large Democrat SUPER PACs expenditures (>$1,000,000) from 2022-24 is " + str(largeDemocratExpendituresDataFrame.size))


totalRepublicanExpenditures = republicanExpendituresDataFrame['exp_amo'].sum()
totalDemocratExpenditures = democratExpendituresDataFrame['exp_amo'].sum()

totalLargeRepublicanExpenditures = largeRepublicanExpendituresDataFrame['exp_amo'].sum()
totalLargeDemocratExpenditures = largeDemocratExpendituresDataFrame['exp_amo'].sum()


print(f"The sum of all large republican expenditures was {totalLargeRepublicanExpenditures}")
print(f"The sum of all large democrat expenditures was {totalLargeDemocratExpenditures}")
#Still need to do more, ex how much of the large donations make up the total donation amount?

The number of Republican SUPER PACs expenditures from 2022-24 is 157525
The number of Democrat SUPER PACs expenditures from 2022-24 is 235450
The number of large Republican SUPER PACs expenditures (>$1,000,000) from 2022-24 is 4375
The number of large Democrat SUPER PACs expenditures (>$1,000,000) from 2022-24 is 4675
The sum of all large republican expenditures was 6732732651.150001
The sum of all large democrat expenditures was 441851678.11